name: Update the Sysdig Operator Repo

on:
  release:
    type: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: update sysdig-operator
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SYSDIG_OPERATOR_ACCESS_TOKEN }}
          repository: sysdiglabs/sysdig-operator
          event-type: sysdig-release
          client-payload: '{"tag": "${{ github.event.release.tag_name }}" }'